### ISSUE TITLE
Piwigo LDAP error

### ISSUE THREAD

**Issue by alfredo87** [Kipjr/ldap_login#103]
The following error appears after updating the LDAP plugin on a yunohost server.

ntents(./plugins/ldap_login/logs/ldap_login.log): Failed to open stream: No such file or directory in /var/www/piwigo/plugins/Ldap_Login/class.ldap.php on line 59

**Comment by Kipjr** [comment]
@alfredo87 which version? can you create this file? The newest version should create this file

**Comment by railsmechanic** [comment]
You can adjust the path to the log directory. Please note the case sensitive `Ldap_Login` path fragment.

![image](https://user-images.githubusercontent.com/682670/227180182-e2588068-0672-4fc5-9866-d6803e9a23f6.png)

**Comment by Kipjr** [comment]
should be fixed with #98 #99 #106 #107 #109
