### ISSUE TITLE
Paths not found

### ISSUE THREAD

**Issue by wwayne007** [Kipjr/ldap_login#106]
By default the plugin installs into a directory called Ldap_Login, but looks for log file in ldap_login.
One work-around was to manually install into a directory named ldap_login.

**Comment by Kipjr** [comment]
@wwayne007 which version do you use?

**Comment by wwayne007** [comment]
?Piwigo 13.6


Regards Warren

________________________________

**Comment by Kipjr** [comment]
What version of this plugin do you use?

**Comment by wwayne007** [comment]
Ldap_Login_13.6.0-be2?

________________________________

**Comment by wwayne007** [comment]
Changing directory name to lower case fixed the log file location error and the activation error, but then could not save the configuration.

If don't use the default directory name, saving config gives the on screen error,  "URL - plugin Ldap_Login not active".

Correcting the path name in the SQL reduces the number of PHP warnings and the log file seems to get written to, but left with this PHP warning:

"PHP Warning:  file_put_contents(./plugins/ldap_login/logs/ldap_login.log): failed to open stream: No such file or directory in /srv/webvol/pubdocs/gallery/plugins/Ldap_Login/class.ldap.php on line 59?". Now only get error on  activation and not on deactivation as well.


________________________________

**Comment by Kipjr** [comment]
this issue is due to the fact that the initial folder name is Ldap_Login but repo is lowercase. I have fixed this by correcting the path to $PLUGIN_ID. I will update asap
