### ISSUE TITLE
Settings not updating

### ISSUE THREAD

**Issue by nnamss** [Kipjr/ldap_login#110]
Hello all o/

I'm doing an internship in a company that would like to use piwigo.
The piwigo server is already set up and up to date however we cannot get the ldap_login to work. 
1st off, as I update the settings in the conf. page, when I hit "Save", it will not keep all the settings update.
For example, it keeps on rolling back to use a "ldaps" protocol when I want to use a simple ldap.

Any work around on this ?

**Comment by Kipjr** [comment]
Due to the recent changes in Piwigo v10+ and Smarty many things broke down. I'm now fixing most of it and planning to release it this week. You could change the settings on SQLDatabase as a workaround
