### ISSUE TITLE
ldap_login Version: 13.6.0 - PHP 7 compatibility 

### ISSUE THREAD

**Issue by AndWalu** [Kipjr/Ldap_Login#115]
- ldap_login Version: 13.6.0

Log:
PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/Gallery/plugins/Ldap_Login/class.ldap.php:79

Function "str_starts_with" was added in PHP 8.

**Comment by Kipjr** [comment]
Thanks I will update my code

**Comment by Kipjr** [comment]
@AndWalu ... PHP7 is EoL.. Please upgrade your environment as  starting of januari 2023 you won't get any security fixes for PHP7.
