### ISSUE TITLE
Trying to mark  	Sync Users  in Group Management	 gives fatal error

### ISSUE THREAD

**Issue by myymi** [Kipjr/Ldap_Login#148]
Good day. I was trying to use Group Management, ticked Sync Users checkbox, clicked Submit, got greeted by this error page. 

Warning: Trying to access array offset on value of type null in /webroot/www/plugins/Ldap_Login/admin/group_management.php on line 295

Warning: foreach() argument must be of type array|object, null given in /webroot/www/plugins/Ldap_Login/admin/group_management.php on line 295

Warning: Undefined variable $activegrouplist in /webroot/www/plugins/Ldap_Login/admin/group_management.php on line 301

Warning: Trying to access array offset on value of type null in /webroot/www/plugins/Ldap_Login/admin/group_management.php on line 301

Fatal error: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /webroot/www/plugins/Ldap_Login/admin/group_management.php:168 Stack trace: #0 /webroot/www/plugins/Ldap_Login/admin/group_management.php(168): implode() #1 /webroot/www/plugins/Ldap_Login/admin/group_management.php(301): sync_usergroups_del() #2 /webroot/www/plugins/Ldap_Login/admin.php(24): include('...') #3 /webroot/www/admin/plugin.php(53): include_once('...') #4 /webroot/www/admin.php(346): include('...') #5 {main} thrown in /webroot/www/plugins/Ldap_Login/admin/group_management.php on line 168

**Comment by myymi** [comment]
Also, trying to mark Create groups, gives this error on the header of the page.


Warning: Undefined array key "groups" in /webroot/www/plugins/Ldap_Login/admin/group_management.php on line 287

Warning: foreach() argument must be of type array|object, null given in /webroot/www/plugins/Ldap_Login/admin/group_management.php on line 62

**Comment by Kipjr** [comment]
The group management feature is deprecated due to the numerous amount of bugs and my limited time for this project

**Comment by myymi** [comment]
Thank You for clarification! That’s actually quite ok for my main purposes, group management is more of a “nice to have” thing. Thanks for the plugin! I myself am not any good on coding, so I really appreciate that.

**Comment by Kipjr** [comment]
I am trying to rewrite the full code in order to include OAuth2 / Azure Entra ID. Maybe that helps. 

I'm just not ready to release it due to I want to review the potential security issues and I'm still not sure whether to include Bootstrap as styling architecture
