### ISSUE TITLE
Message when active Ldap login

### ISSUE THREAD

**Issue by klaoun** [Kipjr/Ldap_Login#149]
hello
#### Important

LDAP Support | enabled
-- | --
Total Links | 0/unlimited
API Version | 3001
Vendor Name | OpenLDAP
Vendor Version | 20447
SASL Support | Enabled
ldap.max_links | Unlimited | Unlimited

**Describe the bug**

**To Reproduce**
when i click config
4. See error : [2024:04:15 01:07:725158] DEBUG: [load_config]> Getting data from SQL table
[ld_table_exist] > SELECT count(*) as count FROM information_schema.TABLES WHERE (TABLE_SCHEMA = 'piwigo') AND (TABLE_NAME = 'piwigo_ldap_login_config')
[ld_table_exist] > Try query on database
[ld_table_exist] > true

**Expected behavior**

**Environment:**

- PHP-Version: 8.3.6
- Piwigo Version: 14.3 and master 11519
- ldap_login Version: 13.8.0
- mysql 8.3
- phpmyadmin 5.2.1

Your configuration:
IIS

php.ini
add extension=ldap

**Logs**
Add part of log here. Please remove any sensitive content

**Comment by klaoun** [comment]
I read in php 8.3 ldap_connect is deprecated
what is possible this error ?

**Comment by Kipjr** [comment]
I dont see an error but just debug logging

Regarding ldap_connect, I think it is the old syntax that is deprecated
