### ISSUE TITLE
Passwords: Extend support for special characters or provide documentation of supported special characters

### ISSUE THREAD

**Issue by dinoschachten-bnitm** [Kipjr/Ldap_Login#155]
Using Piwigo 14.4 with LDAP Plugin 13.8, PHP 8.2.18, connecting to a Microsoft Active Directory.

I can log in with an AD account the password of which contains `!`, but not anymore if I add a `?` to the password. I am aware of issue #22 - in which the recommendation is "not to use an / or an ` in your password" which I understand as these are notoriously tricky to my knowledge.

Since it is generally recommended to use special characters in passwords to increase their complexity, I would assume that a rather common special character as `?` should be supported.

I am not getting any PHP errors, so I am assuming (for now) that this is an actual limitation of the plugin and not a malfunction in our setup...

Here are my questions:

1. Is it actually the case that the plugin does not currently support `?` in passwords (or was I misled by an error in our setup that I haven't yet discovered)?
2. Is there a documentation of supported special characters (I haven't found one)?
3. If `?` is indeed currently not supported: Is it possible to extend support for special characters to minimise compatibility issues and further limitations to desirable password complexity?

**Comment by Kipjr** [comment]
I've done some tests and found out it could be due to PHP escaping stuff:

j$@r`c\oz*v?b"

is written as 

j$@r`c\\\\oz*v?b\\"

in the logs. I will test somewhat more and fix / document it.

**Comment by Kipjr** [comment]
I changed `@ldap_bind($conn,$user,$user_passwd);` to `@ldap_bind($conn,$user,stripslashes($user_passwd));` and got 
![image](https://github.com/Kipjr/Ldap_Login/assets/12066560/59d24934-7090-4c18-bc84-e6934e26237f)

I will commit this for the next update. 

For now it means that slashes and double quotes should be avoided.

**Comment by dinoschachten-bnitm** [comment]
Thanks a lot for looking into this!

Based on your testing with j$@r`c\oz*v?b" it seems that questions marks are not affected by the escaping backslashes - is that correct?

Have you been able to reproduce failed logins with passwords that contain only question marks as well as numbers and letters (no other special characters)?
