### ISSUE TITLE
[Vulnerability] data.dat exposed

### ISSUE THREAD

**Issue by chovyy** [Kipjr/ldap_login#24]
In a normal Piwigo installation, the plugin folders are not blocked. Therefore everyone can view every file in the directories. This is especially serious for the `data.dat` file which may contain sensible data like an AD password.

To see if you are affected, open http(s)://<your_piwigo_installation>/plugins/Ldap_Login/data.dat in your browser.

As a workaround you should advise users to block the access to the file (or the whole plugins(/Ldap_Login) directory) in the server settings or with an .htaccess file. 

A better way would be to store the plugin settings in a php file which will be interpreted by the server and not just displayed.

**Comment by Kipjr** [comment]
Thank you, I will address this issue in the upcoming version.

**Comment by Kipjr** [comment]
Currently I've moved the file to ./config and put an htaccess file there. In the long term, I need to use the SQL-table

**Comment by Kipjr** [comment]
I'm working on a migration towards a SQL table. I did not seem to difficult

**Comment by Kipjr** [comment]
Should be fixed now, transfered to SQL: 37802bb4dbf489b3d93cb785f2c34c993d3252be
