### ISSUE TITLE
trailing ends with ?> in some files

### ISSUE THREAD

**Issue by iNoels** [Kipjr/ldap_login#30]
following files ends with ?>

admin.php
main.inc.php
class.ldap.php

see issue:
https://github.com/Piwigo/Piwigo/pull/643#issuecomment-312656664
and
https://github.com/Piwigo/Piwigo/issues/742

I don't know the root cause, but with ?> endings the file download is corruped with a starting /n (new Line) hex: 0x0a.

**Comment by Kipjr** [comment]
Should be fixed with 4034fa315a5740b8b4c0386fb42dd3a0f3796bc6
