### ISSUE TITLE
ldap_search() error

### ISSUE THREAD

**Issue by sniper9191** [Kipjr/ldap_login#31]
Hi, I am getting this error when trying to 'refresh' the 'Sync settings':
Warning: ldap_search(): Search: Operations error in C:\inetpub\wwwroot\plugins\Ldap_Login\class.ldap.php on line 538

How can this be fixed?
I think my configuration should be correct ('test settings' works fine)

**Comment by Kipjr** [comment]
could you add before line 538, the following:
`$this->make_ldap_bind_as($this->cnx,$this->config['ld_binddn'],$this->config['ld_bindpw'])`

**Comment by Kipjr** [comment]
https://stackoverflow.com/questions/17742751/ldap-operations-error

> I found the problem, was the bind problem. The server accepts the anonymous bind but not the search. And with an user and pass worked but i was making a mistake. For user i considered just de windows's username not the all location from AD, now it works.
> 
> 
> Exact same problem for me. No errors on anonymous binding but then "Warning: ldap_search(): Search: Operations error in.." when searching. Supplying a valid AD user/pass on bind fixed the search. $ldapbind = @ldap_bind($ldapconn, $ldaprdn, $password );
