### ISSUE TITLE
Password not updating

### ISSUE THREAD

**Issue by xaero27** [Kipjr/ldap_login#37]
Hello! 

Great plugin! But I experienced that the password is not being updated if changed by the user in LDAP. 
Is there a possibility to force a validity check with the LDAP server every time at login? 

Kind regards
Fabian

**Comment by Kipjr** [comment]
Please check https://github.com/Kipjr/ldap_login/tree/dev for the most recent update.

When Ldap_Login is enabled, then the following happens (next step will only happen when positive current step)

> 1. Check for min length username / password
> 
> 2. Try to connect to Ldap (but not yet bind)
> 
> 3. Try to search username in  LDAP Server and if found, try to connect with supplied username / password to bind with LDAP Server
> 
> 5. Try to find user in Piwigo database and if not found create user, else check for changes in user rights. 
> 

So to answer your question, it already happens. There is no password in the Piwigo database
