### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by risiko79** [Kipjr/ldap_login#38]
If I  activate the ldap plugin i get this warning:

: Cannot modify header information - headers already sent by (output started at /piwigo/plugins/Ldap_Login/class.ldap.php:551) in
/piwigo/include/page_header.php
on line
86

The plugin itself works well. 

Versions: php: 7.3.19-1, piwigo 2.10.2, ldap plugin: 2.10c

Risiko

**Comment by Kipjr** [comment]
I will look into it

**Comment by Kipjr** [comment]
Fixed with https://github.com/Kipjr/ldap_login/commit/bd5f47a6a919de0440338f3bf32b6ee55f0f9cc3
