### ISSUE TITLE
Problem with serialize function and connection credentials

### ISSUE THREAD

**Issue by ghost** [Kipjr/Ldap_Login#47]
Hi,

I have an issue with the set up page. We want to verify the users using Active Directory on a Windows Server, so far without LDAPS.

The issue seems to be with reading and processing the credentials.

The username we need to use contains a backslash and this seems to be an issue because most likely during serialization and subsequent unserialization, this backslash is treated very strangely. When looking at the log file, at various phases of the script the backslash is converted to either "5C" or another backslash. The final username saved to the db contains two backslashes instead of one. This of course leads to a failed connection.

Is there a way to make the script treat backslash correctly in username?

**Comment by Kipjr** [comment]
normally the "\" is a reserved character to use for escaping other characters or for the glue between a DOMAIN and USER i.e. GITHUB.COM\Username

Is this the case for your situation?

**Comment by jachymcz** [comment]
Hi,
yes this is exactly our situation, for the bind DN parameter we need to use a domain + back slash + username. But the back slash is not treated properly by the script and it fails to bind to the LDAP.

**Comment by Kipjr** [comment]
If you have configured your system correctly this should not be the case

I have username kipjr on domain abc.def 
My DN is cn=kipjr,ou=users,dc=abc,dc=def
I logon to windows using abc\kipjr
Bit on piwigo I only need my username kipjr

Is this situation similar for you?

**Comment by jachymcz** [comment]
Thanks for your help, we made some changes to make the above work and it is now ok!
