### ISSUE TITLE
using in current piwigo version (12.1)

### ISSUE THREAD

**Issue by expresik** [Kipjr/ldap_login#59]
Is it possible to use the plugin in current piwigo version? I have it just fresh installed, ldap is ready also and... I cannot bring it to work.

**Comment by Kipjr** [comment]
I'm working on an update it. Can you show me what errors you get?

**Comment by expresik** [comment]
Hmmm... I've tried with dev version and my whole piwigo died. Not sure whether this was the reason, but now I can see (instead of piwigo):

`
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/piwigo/include/common.inc.php on line 126

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /var/www/html/piwigo/include/functions.inc.php:720 Stack trace: #0 /var/www/html/piwigo/include/functions.inc.php(720): DateTime->__construct() #1 /var/www/html/piwigo/include/functions.inc.php(828): str2DateTime('2021-12-31 02:4...', NULL) #2 /var/www/html/piwigo/themes/modus/themeconf.inc.php(305): time_since('2021-12-31 02:4...', 'month') #3 [internal function]: modus_index_category_thumbnails(Array) #4 /var/www/html/piwigo/include/functions_plugins.inc.php(214): call_user_func_array('modus_index_cat...', Array) #5 /var/www/html/piwigo/include/category_cats.inc. in /var/www/html/piwigo/include/functions.inc.php on line 720`

Today or tomorrow I will reinstall piwigo and I can try from scratch. 
Luckily, it was completely fresh and empty, so, no loss on my side :)

When reinstalled, I'm good to help and work on that.

**Comment by Kipjr** [comment]
can you fill in the bug report, it make it a lot more clear. Also PHP7.x and 8.1 are somewhat different. I would recommend using 8.1 from now on

**Comment by Kipjr** [comment]
can you fill in the bug report, it make it a lot more clear. Also PHP7.x and 8.1 are somewhat different. I would recommend using 8.1 from now on
